### ISSUE TITLE
cython related error when building docs on Readthedocs

### ISSUE THREAD

**Issue by NiklasRosenstein** [craftr-build/craftr#124]
```
Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/craftr/envs/stable/lib/python3.4/site-packages/sphinx/ext/autodoc.py", line 385, in import_object
    __import__(self.modname)
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1191, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1161, in _load_backward_compatible
  File "/home/docs/checkouts/readthedocs.org/user_builds/craftr/envs/stable/lib/python3.4/site-packages/craftr_build-1.0.0-py3.4.egg/craftr/ext.py", line 221, in load_module
    exec(compile(fp.read(), self.filename, 'exec'), vars(module))
  File "/home/docs/checkouts/readthedocs.org/user_builds/craftr/envs/stable/lib/python3.4/site-packages/craftr_build-1.0.0-py3.4.egg/craftr/lib/compiler.cython.craftr", line 69, in <module>
    cythonc = CythonCompiler()
  File "/home/docs/checkouts/readthedocs.org/user_builds/craftr/envs/stable/lib/python3.4/site-packages/craftr_build-1.0.0-py3.4.egg/craftr/lib/compiler.cython.craftr", line 40, in __init__
    output = craftr.shell.pipe([program, '-V']).output
  File "/home/docs/checkouts/readthedocs.org/user_builds/craftr/envs/stable/lib/python3.4/site-packages/craftr_build-1.0.0-py3.4.egg/craftr/shell.py", line 194, in pipe
    return run(*args, **kwargs)
  File "/home/docs/checkouts/readthedocs.org/user_builds/craftr/envs/stable/lib/python3.4/site-packages/craftr_build-1.0.0-py3.4.egg/craftr/shell.py", line 161, in run
    cmd, stdin=stdin, stdout=stdout, stderr=stderr, shell=shell, cwd=cwd)
  File "/usr/lib/python3.4/subprocess.py", line 859, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.4/subprocess.py", line 1457, in _execute_child
    raise child_exception_type(errno_num, err_msg)
FileNotFoundError: [Errno 2] No such file or directory: 'cython'
```

**Comment by NiklasRosenstein** [comment]
No read-the-docs for Craftr 2.x so far, closed until issue re-appears
