### ISSUE TITLE
MSVC on Appveyor: AssertionError when detecting MSVC installation

### ISSUE THREAD

**Issue by NiklasRosenstein** [craftr-build/craftr#157]
```
Traceback (most recent call last):
  File "C:\Python35\Scripts\craftr-script.py", line 9, in <module>
    load_entry_point('craftr-build==2.0.0.dev4', 'console_scripts', 'craftr')()
  File "c:\python35\lib\site-packages\craftr\__main__.py", line 407, in main_and_exit
    sys.exit(main())
  File "c:\python35\lib\site-packages\craftr\__main__.py", line 403, in main
    return commands[args.command].execute(parser, args)
  File "c:\python35\lib\site-packages\craftr\__main__.py", line 213, in execute
    module.run()
  File "c:\python35\lib\site-packages\craftr\core\session.py", line 430, in run
    exec(code, vars(self.namespace))
  File "C:\projects\cpp-nr\craftr\Craftrfile", line 20, in <module>
    load_module('craftr.lang.cxx.*')
  File "c:\python35\lib\site-packages\craftr\defaults.py", line 204, in load_module
    loaded_module.run()
  File "c:\python35\lib\site-packages\craftr\core\session.py", line 430, in run
    exec(code, vars(self.namespace))
  File "c:\python35\lib\site-packages\craftr\stl\craftr.lang.cxx\Craftrfile", line 32, in <module>
    cxc = load_module(module).cxc
  File "c:\python35\lib\site-packages\craftr\defaults.py", line 204, in load_module
    loaded_module.run()
  File "c:\python35\lib\site-packages\craftr\core\session.py", line 430, in run
    exec(code, vars(self.namespace))
  File "c:\python35\lib\site-packages\craftr\stl\craftr.lang.cxx.msvc\Craftrfile", line 514, in <module>
    cxc = msvc = MsvcToolkit()
  File "c:\python35\lib\site-packages\craftr\stl\craftr.lang.cxx.msvc\Craftrfile", line 284, in __init__
    self.install_info = find_installation(version, target or real_arch)
  File "c:\python35\lib\site-packages\craftr\stl\craftr.lang.cxx.msvc\Craftrfile", line 194, in find_installation
    vsversion = vsvar[2:5]; assert(all(c.isdigit() for c in vsversion))
AssertionError
```

**Comment by NiklasRosenstein** [comment]
Can be closed with 7a62005
