### ISSUE TITLE
Travis CI + OSX: Operation not supported by device

### ISSUE THREAD

**Issue by NiklasRosenstein** [craftr-build/craftr#169]
I am not sure if this broke due to a change in Craftr or the Travis CI environment. Lately, I get the following error when using OSX on Travis. It does not appear on Linux. What I do know is that we don't actually get a propery terminal size in the Travis build environment (likely because the build is not attached to a TTY (or not a *real* TTY?)). 

```
$ craftr export -d .version=$C4DVERSION
Traceback (most recent call last):
  File "/usr/local/bin/craftr", line 11, in <module>
    load_entry_point('craftr-build==2.0.0.dev5', 'console_scripts', 'craftr')()
  File "/usr/local/lib/python3.6/site-packages/craftr/__main__.py", line 742, in main_and_exit
    sys.exit(main())
  File "/usr/local/lib/python3.6/site-packages/craftr/__main__.py", line 738, in main
    return commands[args.command].execute(parser, args)
  File "/usr/local/lib/python3.6/site-packages/craftr/__main__.py", line 239, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/craftr/__main__.py", line 348, in execute
    return self._export_run_or_help(args, module)
  File "/usr/local/lib/python3.6/site-packages/craftr/__main__.py", line 404, in _export_run_or_help
    module.run()
  File "/usr/local/lib/python3.6/site-packages/craftr/core/session.py", line 451, in run
    exec(code, vars(self.namespace))
  File "/Users/travis/build/craftr-build/NiklasRosenstein.maxon.c4d/Craftrfile", line 47, in <module>
    options.directory = external_archive(options.url)
  File "/usr/local/lib/python3.6/site-packages/craftr/loaders.py", line 203, in external_archive
    archive = external_file(*urls, directory = directory, name = name)
  File "/usr/local/lib/python3.6/site-packages/craftr/loaders.py", line 157, in external_file
    progress = progress)
  File "/usr/local/lib/python3.6/site-packages/craftr/utils/httputils.py", line 105, in download_file
    if progress and progress(progress_info) is False:
  File "/usr/local/lib/python3.6/site-packages/craftr/loaders.py", line 152, in <lambda>
    progress_info, directory, filename, cache, data)
  File "/usr/local/lib/python3.6/site-packages/craftr/loaders.py", line 62, in _external_file_download_callback
    logger.progress_begin(progress_text, is_spinning)
  File "/usr/local/lib/python3.6/site-packages/craftr/core/logging.py", line 142, in progress_begin
    self.info(description)
  File "/usr/local/lib/python3.6/site-packages/craftr/core/logging.py", line 42, in info
    self.log(INFO, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/craftr/core/logging.py", line 110, in log
    width = tty.terminal_size()[0] - 1
  File "/usr/local/lib/python3.6/site-packages/craftr/utils/tty.py", line 75, in terminal_size
    struct.pack('HHHH', 0, 0, 0, 0)))
OSError: [Errno 19] Operation not supported by device
```

**Comment by NiklasRosenstein** [comment]
Likely an issue with this line in `terminal_size()`

    data = fcntl.ioctl(0, termios.TIOCGWINSZ, struct.pack('HHHH', 0, 0, 0, 0))

Added fc8d0e2 to confirm on TravisCI.
