### ISSUE TITLE
Exception in Craftfile leads to "Bad file descriptor" in daemon thread

### ISSUE THREAD

**Issue by NiklasRosenstein** [craftr-build/craftr#56]
This happens not every time, but most of the time when an exception occurs in a Craftfile.

```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.4/threading.py", line 920, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.4/threading.py", line 868, in run
    self._target(*self._args, **self._kwargs)
  File "/home/niklas/Desktop/craftr/craftr/daemon.py", line 505, in serve_forever
    self.sock.listen(listen)
OSError: [Errno 9] Bad file descriptor
```

**Comment by NiklasRosenstein** [comment]
Not reproducable.
